### ISSUE TITLE
Looking at Signal Bus causes crash

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#212]
I placed a Signal Bus then the client crashed. Another player came over and crashed as soon as he went to mine it up. I tried to join twice and crashed both time. After reading the crash log, it said that the crash was likely caused by WAILA, so when I reconnected I tried moving and it worked. So as far as I can tell WAILA causes you to crash if you look at a Tinkers' Mechworks Signal Bus.

http://openeye.openmods.info/crashes/14a3b48de24e3abf3d736f444a5df056

**Comment by BBoldt** [comment]
Well shit. 

     On Friday, January 9, 2015 11:51 PM, Fuhrmaaj <notifications@github.com> wrote:
   

 I placed a Signal Bus then the client crashed. Another player came over and crashed as soon as he went to mine it up. I tried to join twice and crashed both time. After reading the crash log, it said that the crash was likely caused by WAILA, so when I reconnected I tried moving and it worked. So as far as I can tell WAILA causes you to crash if you look at a Tinkers' Mechworks Signal Bus.http://openeye.openmods.info/crashes/14a3b48de24e3abf3d736f444a5df056—

**Comment by BBoldt** [comment]
wow, replying by email does some weird shit

**Comment by BBoldt** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2169830-wawla-what-are-we-looking-at?comment=158

**Comment by BBoldt** [comment]
Removing Wawla until the issue is resolved.
