### ISSUE TITLE
Rework crop breeding system to make bees not obsolete

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#297]
Also, port the IC2 crops

**Comment by Fuhrmaaj** [comment]
I think it's important to consider that a player who does apiculture:
- can only have 1 hive per princess
- needs to spend seed oil in order to get any kind of output (apiaries, frames, etc)
- output increases with alvearies which use resources discovered within forestry (honey, imperial jelly)
- can save seed oil by switching to RF eventually
- must isolate the species trait on mutations before any real work can be done
- runs the risk of destroying bees when messing with genetics in gendustry
- must consider bees with negative effects which destroy terrain and kill or debuff the player; beesuits are a pain to get and not even guaranteed protection
- will mutate many species which produce wax, propolis, honey or imperial jelly; all of which are only valuable within the mod. These species are necessary steps on the path to the species you actually want.

Most of these cannot be replicated in Agricraft. Considering these facts, I think the goal should be to making bees more useful than Agricraft, otherwise they are necessarily obsolete because Agricraft is easier to do. Slowing the production rate only means that an Agricraft user needs to make more plants to meet their required production, which is only a factor for plants which require rare ores below them in order to produce.

Some ideas for Agricraft:

1) Turn weeds on. It's hard to complain about balance when the mod isn't being played as intended. In IC2 it was possible to avoid weeds destroying everything by separating the mutating crops from the production crops. If the behaviour is identical then this shouldn't wipe out everything you've grown, but if you're not watching then weeds could take out your mutating plants.

2) Require a rare soil, or something that requires work for non-vanilla plants. Examples might be Random Things Fertilized Dirt or Forestry's Humus. If you want to balance against bees, you could make a new type of ore (example: gaianite) which must be crafted into each soil block. This is how princesses function in Forestry.

3) Make the recipe for crops something that requires some infrastructure. I think a good idea would be to make crops crafted from Impregnated Sticks because Forestry's frames are crafted from Impregnated Sticks.

4) Have random plants scattered through the tech tree which don't require ores so that mutations might produce plants which aren't as valuable to players.

5) Change the recipe for the irrigation system to require a resource which can only be acquired from a new plant added to Agricraft. For example, the "Imperial Flower" produces "lump of plant sap", craft nine of those together for a ball of plant sap which is required in the water tank and channels, 4 balls of plant sap for the sprinkler. This means you must use the mod for a while before you get the increased production rate provided by the irrigation system.

6) Intentionally leave some resources to bees. If bees are the only way to get mob drops, then they've always got a niche use. An example of why this is necessary is Thaumcraft shards, which are a massive pain to get in apiculture, but they seem super easy in Agricraft. Half the shard bees kill players fairly quickly and each  species requires 9 "useless" mutations, plus 2 per species you want (11 for air shards, 13 for air and fire shards, etc.). The process is just so much easier in Agricraft.

**Comment by BBoldt** [comment]
1) Done.

2) I can't quite accomplish this right now.

3) Done.

4) Done kinda, I might need help with ideas for this in the future.

5) No. I can't do this without completely breaking the recipes and having to readd them for each wood type.

6) Okay, I'll take some out. The method for getting the shards is much more unique and interesting in apiculture.

Closing this issue for now until I decide to work on the crop system again.
