### ISSUE TITLE
java.lang.NullPointerException: Ticking screen

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#481]
http://pastebin.com/cMWywR0a

Only seems to happen on release 10 when connecting to a server.

Solution is to join a single player world before connecting to any servers.

More info here: https://www.reddit.com/r/MinecraftUnabridged/comments/41jd5c/server_issues/

**Comment by leezallen** [comment]
I don't know if this helps you at all in solving the issue (you have probably already got it hand) but from looking at error in the client log rather than in the crash report there are three mods that seem to be contributing (or are at least referenced with warnings) - Galacticraft, Not Enough Resources and Reliquary.

I can confirm that disabling Reliquary resolves this issue. Although I am not 100% sure why this would be the case!

Hope this helps!

**Comment by BBoldt** [comment]
Really! I did update reliquary recently after I noticed I hadn't updated it in months and months, maybe there *was* a reason I never updated it.

**Comment by leezallen** [comment]
If you would like I do not mind doing some testing to see if there is the same issue with the older version. Have been putting modpacks together for a while so I know all of the ins and outs. Will grab the older config from the GitHub... If you would like to let me know what version was being used before and I will let you know what the outcome is (and if there are any other issues from rolling back).

Just thought it might spare you some time!

**Comment by BBoldt** [comment]
Would appreciate it, been busy with other things the last couple weeks.

Forget the configs, just download Release 9 and copy over the Reliquary and LibSandstone from that.

**Comment by leezallen** [comment]
Will do. I will let you know how it goes.

**Comment by leezallen** [comment]
OK.... From what I can see Reliquary and LibSandstone is a nightmare!!!! The long and the short of it is that it works if you revert ** both of these files ** back to the version found in Modpack version 9! 

It has to be both of the files though because even though LibSandstone is listed as version 1.0.0 it crashes with a complaint about API references.... It seems that not all 1.0.0s are equal (even though they are the same size)!!!! (The crash even occurs if you delete LibSandstone and let it download a new one!)

From what I can see though the mod and library is regularly updated but minor version numbers are not changed on the mod when these small updates are applied!  For instance Reliquary itself has been updated 9 times since your pack update but it still listed as the same version number! 

Tried various combinations of both mod and library from the build server but could not get one that would work together. I would suspect that the issue is that LibSandstone has implemented some GuiHooks which is conflicting with the other mods mentioned earlier but that is just speculation at this point!

Just in case you want to have a look at the error that shows up in the client-log (which is much more helpful that the crash report!) you can find it on pastebin here - http://pastebin.com/bf16z2LD

I hope that is partially helpful to you! If you are ever find yourself in "issue overload" or just want some help on anything then let me know and I will help out where I can.

**Comment by dredhorse** [comment]
@leezallen thanks for figuring that out, somebody should probably tell the mod developer that he should implement proper versioning.

**Comment by BBoldt** [comment]
Fixed in Release 10a
