### ISSUE TITLE
[v10] Stone/Flint Tools Broken

### ISSUE THREAD

**Issue by gr8pefish** [BBoldt/Unabridged#484]
Stone and flint tools are unable to mine what they should, no items drop. For example, stone pick -> coal ore -> nothing. The block is mined but you receive no coal. Note that this was with vanilla stone picks.

I haven't done extensive testing, this was just what we noticed on our fresh install (note that it was on a server).

Edit: I had all optional mods installed.

**Comment by okyriosy** [comment]
The issue seems to be with servers and multiple ores. It is not present in singleplayer

**Comment by Axelandre42** [comment]
Yeah ! I've got also this issue !

**Comment by assasinwar9** [comment]
yep... iron pickaxe works fine but stome flint and bronze dont seem to work >.>

**Comment by okyriosy** [comment]
Other picks are affected, like a steel pick being unable to harvest obsidian.

**Comment by tommyTT** [comment]
I also have this issue. Funny thing is that I sometimes only need to switch to another pickaxe (stone -> dark steel) in my hotbar after mining a block and the mined block drops as an item.
I have another problem, that doesn't allow me to break anything with my hand: not dirt, not leaves, not my grave stone. This is a big problem, because I can't even get my stuff out of the storage drawers by hitting it with my hand. Can this be related? I'm playing on a completely new server instance with all the optional mods enabled.

**Comment by DeGariless** [comment]
Tommytt. Try the command /gamemode 1.
Does that fix your hand punching problem?

**Comment by tommyTT** [comment]
Thank you for the answer, yesterday I figured it out myself. Somehow the "canBuild" NBT Data on my player was set to false, but I have no idea why. I never switched gamemodes before but going into creative mode and back fixed it. It is so nice to finally be able to get stuff out of my storage drawers again without needing a tool in my hand.
The issue with the mining levels however is not affected by this unfortunately.

**Comment by DeGariless** [comment]
Removing RFdrills from the server, or both server and client fixes this issue.

**Comment by jkoelndorfer** [comment]
From what I've seen, this seems to be an issue with Iguana Tweaks and multiplayer. Disabling this mod on client and server side fixes all the ore breaking bugs (stone pick -> iron ore, bronze pick -> certus quartz, etc).

Unfortunately you don't get the cool ore progression and you lose out on Iguana Tweaks features.
