### ISSUE TITLE
Igneous Extruder Augments not working

### ISSUE THREAD

**Issue by cHaOZZoNE** [BBoldt/Unabridged#512]
Newest version
[See this gif.](https://gyazo.com/0f28be1168e1797ff8154eb1e9854c20)

To reproduce: Get upgraded Igneous Extruder. Shove Augments in. Augments not doing anything (see gif).

**Comment by adegarimore** [comment]
That's because there was only 1 bucket of lava in there. the machine will only make 1 obby with 1 bucket of lava. If it had 8 buckets, it would be able to make 8 at once.

Steps to prove that it's not a bug.
1. turn off igneous extruder via redstone (set to work only with redstone signal)
2. Put in 8 buckets of lava
3. Turn machine back on via redstone
   4 receive 8 obsidian all at once

**Comment by BBoldt** [comment]
"Newest version"?
Follow the issue template or don't report issues.

As @DeGariless said, it's not a bug.
