### ISSUE TITLE
[1.10.2][Abridged][Request] Gendustry Mod

### ISSUE THREAD

**Issue by Aedda** [BBoldt/Unabridged#544]
Bees are great and all but they are so much more with Gendustry. Myself and at least one other were surprised it wasn't included since Forestry was.

**Comment by BBoldt** [comment]
It kinda ruins the progression of forestry to be honest. That, coupled with the bad textures, is why I didn't include it in "Abridged". Not to mention i'm trying to keep the pack a bit minimalistic, meaning every mod isn't going to get lots of addons, otherwise I would be doing "Unabridged" still.

I've always been more of a fan of the content added by Binnie's Mods, and would rather go in that route if I were even considering adding a forestry addon to Abridged.

**Comment by BBoldt** [comment]
Gonna go ahead and close this. Gendustry will be in Unabridged when it happens.

**Comment by Aedda** [comment]
Since an Unabridged is planned then I will concede but I wanted to point out the mod More Bees. All it does is add more bees. It would obviously make bees more useful and more involved and give an alternative to digitial miners for everything.

**Comment by BBoldt** [comment]
More Bees looks fun, I'll consider it!
