### ISSUE TITLE
EnderIO farming station with Agricraft

### ISSUE THREAD

**Issue by Pandoras-end-network** [BBoldt/Unabridged#643]
**Minecraft version:**
1.7.10 (on a latest thermos server)

**Unabridged or Abridged version:**
Unabridged 

**Issue Description:**
When the EnderIO Farming Station Farms an agricraft crop from a crop stick it converts the seeds back to 1/1/1. In older versions there was a Agricraft Farming Station, but it seems to be gone now

**Steps to Reproduce:**
1. Place EnderIO farming station
2. Power it.
3. Place Cropsticks.
4. Plant seeds that are higher then 1/1/1

**Crash report or log (uploaded to gist.github.com or pastebin.com):**
No crash, nothing in log

**Comment by BBoldt** [comment]
I don't know if it was just endercore or the combination of endercore+enderio+enderioaddons causing this, but I took Ender IO Addons out of the pack to isolate EnderIO because of this issue:

https://github.com/BBoldt/Unabridged/issues/618

I can't use the patched version of endercore that's listed in that thread because I am not allowed to upload it on curseforge. 

So until I figure out how to solve this, or if it is even still an issue for people in 2020, EnderIO is rolling solo.
