### ISSUE TITLE
Matmos yelling all the time in chat

### ISSUE THREAD

**Issue by BBoldt** [BBoldt/Unabridged#651]
**Minecraft version:**
1.7.10
**Unabridged or Abridged version:**
3.19.1
**Issue Description:**
Matmos crashing, yelling about it in chat.

![image](https://user-images.githubusercontent.com/1463458/105007080-649b8600-59ec-11eb-93c3-de557a909427.png)
![image](https://user-images.githubusercontent.com/1463458/105007128-741acf00-59ec-11eb-9e4c-cba71332c183.png)

Looks like this is caused by Matmos interacting with Not Enough IDs, and there is a solution posted here:
https://github.com/makamys/MAtmos/issues/5

I'll fix the config file as soon as I can. Also I'll probably make Matmos optional on ATLauncher.

**Comment by BBoldt** [comment]
Actually I don't know if it's the same issue but the pack *does* have NEID. I need to get an actual log, these are only screenshots provided to me by users.

**Comment by maggi373** [comment]
for whats its saying, its probably neid because its the only thing that extends the id range and its complaining thats its out of bounds.

Thrown to indicate that an array has been accessed with an illegal index. The index is either negative or greater than or equal to the size of the array.

edit: i just checked matmos code and its indeed neid causing this problem. Matmos has an int that is cointaining max id. ill be posting a fix in few moments

**Comment by BBoldt** [comment]
Don't do PRs for things I'm already working on please, and also don't submit PRs that are just single line config changes, it's not very helpful. Thanks for trying to help though.

I knew about that fix already because I already researched it, the solution is posted in the thread I linked. 
I'm not setting it to 65535, I'm setting it to 8192 as suggested by @makamys, who is the current maintainer of matmos. There definitely isn't more than 8192 blocks in the pack, setting it so high could cause other issues.

**Comment by Pandoras-end-network** [comment]
MAtmos still yells when its set to world.maxblockid=8192. A player reported it but has no clue what could have caused it around him.
